# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 190)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_text_task = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_text_task.setFont(font)
        self.lb_text_task.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_text_task.setObjectName("lb_text_task")
        self.verticalLayout.addWidget(self.lb_text_task)
        self.lb_text_userans = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_text_userans.setFont(font)
        self.lb_text_userans.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_text_userans.setObjectName("lb_text_userans")
        self.verticalLayout.addWidget(self.lb_text_userans)
        self.lb_text_result = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_text_result.setFont(font)
        self.lb_text_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_text_result.setObjectName("lb_text_result")
        self.verticalLayout.addWidget(self.lb_text_result)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_task = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_task.setFont(font)
        self.lb_task.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.lb_task.setAutoFillBackground(True)
        self.lb_task.setText("")
        self.lb_task.setWordWrap(True)
        self.lb_task.setObjectName("lb_task")
        self.verticalLayout_2.addWidget(self.lb_task)
        self.le_userans = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_userans.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_userans.setFont(font)
        self.le_userans.setText("")
        self.le_userans.setObjectName("le_userans")
        self.verticalLayout_2.addWidget(self.le_userans)
        self.lb_result = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_result.setFont(font)
        self.lb_result.setAutoFillBackground(True)
        self.lb_result.setText("")
        self.lb_result.setWordWrap(True)
        self.lb_result.setObjectName("lb_result")
        self.verticalLayout_2.addWidget(self.lb_result)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_start_stop = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_start_stop.setFont(font)
        self.btn_start_stop.setObjectName("btn_start_stop")
        self.verticalLayout_3.addWidget(self.btn_start_stop)
        self.btn_ok = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_ok.setFont(font)
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout_3.addWidget(self.btn_ok)
        self.btn_exit = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_3.addWidget(self.btn_exit)
        self.horizontalLayout.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MEME Trainer"))
        self.lb_text_task.setText(_translate("MainWindow", "Task"))
        self.lb_text_userans.setText(_translate("MainWindow", "Answer"))
        self.lb_text_result.setText(_translate("MainWindow", "Result"))
        self.btn_start_stop.setText(_translate("MainWindow", "Start"))
        self.btn_ok.setText(_translate("MainWindow", "OK"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
